# Generated by Django 2.2.6 on 2019-11-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_for_verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('fnlwgt', models.PositiveIntegerField()),
                ('education_num', models.PositiveIntegerField()),
                ('capital_gain', models.PositiveIntegerField()),
                ('capital_loss', models.PositiveIntegerField()),
                ('hours_per_week', models.PositiveIntegerField()),
                ('workclass_Private', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('workclass_Self_emp_not_inc', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('workclass_Local_gov', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('workclass_question_mark', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('workclass_State_gov', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('marital_status_Married_civ_spouse', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('marital_status_Never_married', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('occupation_Prof_specialty', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('occupation_Craft_repair', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('occupation_Exec_managerial', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('occupation_Adm_clerical', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('occupation_Sales', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('occupation_Other_service', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('occupation_Machine_op_inspct', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('occupation_question_unk', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('occupation_Transport_moving', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('relationship_Husband', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('relationship_Not_in_family', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('relationship_Own_child', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('relationship_Unmarried', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('race_White', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
                ('sex_Male', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=20)),
            ],
        ),
    ]
